name: flutter_mongodb_realm
description: Unofficial plugin for using services of the serverless platform MongoDB Realm.
version: 1.0.0+1
homepage: https://github.com/tapLab/flutter_mongodb_realm
publish_to: none

environment:
    sdk: ">=2.7.0 <3.0.0"
    flutter: "2.10.5"

dependencies:
    flutter:
        sdk: flutter

    flutter_mongo_realm_platform_interface:
        git: https://github.com/tapLab/flutter_mongo_realm_platform_interface.git
    # The design on https://flutter.dev/go/federated-plugins was to leave
    # this constraint as "any". We cannot do it right now as it fails pub publish
    # validation, so we set a ^ constraint.
    flutter_mongo_realm_web:
        git: https://github.com/tapLab/flutter_mongo_stitch_web.git

    universal_html: ^2.0.8 # instead importing in runtime
    bson: ^1.0.4
    extension: ^0.4.0
    streams_channel: ^0.3.0
    meta: ^1.7.0

dev_dependencies:
    flutter_test:
        sdk: flutter

flutter:
    plugin:
        platforms:
            android:
                package: com.example.flutter_mongo_realm
                pluginClass: FlutterMongoRealmPlugin
            ios:
                pluginClass: FlutterMongoRealmPlugin
            web:
                default_package: flutter_mongo_realm_web
